name: Run CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build-dists:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
        with:
          python-version: 3.12
      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Build distributions
        run: python -m build --no-isolation
      - name: Upload distributions
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
        with:
          name: release-dists
          path: dist/
  check-sdist:
    name: Check sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
        with:
          python-version: 3.12
      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Run check-manifest
        run: check-manifest --no-build-isolation
